"""Regenerate the tables in LIMITATIONS.md by calling the real implementation.

Run it, then paste the output into the document. No number in LIMITATIONS.md is
hand-written; if one looks wrong, fix the library or this script, not the prose.

    uv run python docs/make_error_tables.py
"""

from __future__ import annotations

import numpy as np

from cam2geo import SETUPS, position_error

#: What a detector's or annotator's error is worth, in pixels.
PIXEL_SIGMA = 1.0
#: Pointing uncertainty: mast sway, thermal drift, a bumped bracket.
POINTING_SIGMA_DEG = 0.05
#: A survey good enough to be unremarkable.
CONTROL_RMS_PX = 2.0


def _rows(view, count: int = 8) -> np.ndarray:
    """Image rows from the bottom edge up to just past the conditioning cutoff."""
    candidates = np.arange(view.height - 1.0, 0.0, -1.0)
    cols = np.full(candidates.size, view.width / 2.0)
    gsd = view.ground_m_per_px(cols, candidates)
    usable = candidates[np.isfinite(gsd) & (gsd <= 50.0)]
    return usable[np.linspace(0, usable.size - 1, count).astype(int)]


def error_table(setup) -> str:
    """One setup's error budget, as a markdown table."""
    view = setup.station.view
    rows = _rows(view)
    cols = np.full(rows.size, view.width / 2.0)
    surface = setup.surface.but(offset_m=0.0, offset_sigma_m=max(
        setup.surface.offset_sigma_m, 0.5))
    budget = position_error(setup.station, cols, rows, surface,
                            pixel_sigma_px=PIXEL_SIGMA,
                            pointing_sigma_deg=POINTING_SIGMA_DEG,
                            control_rms_px=CONTROL_RMS_PX)

    out = ["| image row | range m | m/px | 1 px | height sigma | roughness "
           "| pointing | control | random | bias | total |",
           "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for i, row in enumerate(rows):
        cells = [f"{row:.0f}", f"{budget.range_m[i]:.0f}",
                 f"{budget.pixel_m[i]:.3f}", f"{budget.pixel_m[i]:.2f}",
                 f"{budget.height_sigma_m[i]:.2f}", f"{budget.roughness_m[i]:.2f}",
                 f"{budget.pointing_m[i]:.2f}", f"{budget.control_m[i]:.2f}",
                 f"{budget.random_m[i]:.2f}", f"{budget.bias_m[i]:.2f}",
                 f"**{budget.total_m[i]:.2f}**"]
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out)


def dominant_term(setup) -> str:
    """Which term is largest at each range, which is the point of the document."""
    view = setup.station.view
    rows = _rows(view, count=6)
    cols = np.full(rows.size, view.width / 2.0)
    surface = setup.surface.but(offset_m=0.0, offset_sigma_m=max(
        setup.surface.offset_sigma_m, 0.5))
    budget = position_error(setup.station, cols, rows, surface,
                            pixel_sigma_px=PIXEL_SIGMA,
                            pointing_sigma_deg=POINTING_SIGMA_DEG,
                            control_rms_px=CONTROL_RMS_PX)
    names = ["1 px", "height sigma", "roughness", "curvature", "pointing", "control"]
    terms = np.vstack([budget.pixel_m, budget.height_sigma_m, budget.roughness_m,
                       budget.curvature_m, budget.pointing_m, budget.control_m])

    out = ["| range m | dominant term | it is worth | total |", "|---:|---|---:|---:|"]
    for i in range(rows.size):
        worst = int(np.nanargmax(terms[:, i]))
        out.append(f"| {budget.range_m[i]:.0f} | {names[worst]} "
                   f"| {terms[worst, i]:.2f} m | {budget.total_m[i]:.2f} m |")
    return "\n".join(out)


def reach_table() -> str:
    """How far each setup reaches before conditioning passes a threshold."""
    out = ["| setup | horizon row | 0.1 m/px | 1 m/px | 10 m/px |",
           "|---|---:|---:|---:|---:|"]
    for make in SETUPS:
        setup = make()
        view = setup.station.view
        line = view.horizon_line
        horizon_row = -(line[0] * view.width / 2.0 + line[2]) / line[1]
        reaches = []
        for cutoff in (0.1, 1.0, 10.0):
            ring = view.footprint(max_m_per_px=cutoff)
            reaches.append(f"{np.abs(ring[:, 1]).max():.0f} m"
                           if len(ring) else "--")
        out.append("| `{}` | {:.0f} | {} |".format(
            setup.name, horizon_row, " | ".join(reaches)))
    return "\n".join(out)


def main() -> None:
    print("<!-- generated by docs/make_error_tables.py -- do not hand-edit -->\n")
    print("## Reach\n")
    print(reach_table())
    for make in SETUPS:
        setup = make()
        print("\n\n## " + setup.name + "\n")
        print("_" + setup.description + "_\n")
        print(error_table(setup))
        print("\nDominant term by range:\n")
        print(dominant_term(setup))


if __name__ == "__main__":
    main()
